
[functions.visa-mastercard]
enabled = true
verify_jwt = false
entrypoint = "./functions/visa-mastercard/index.ts"

[functions.payment-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/payment-webhook/index.ts"

[functions.test-payment-gateway]
enabled = true
verify_jwt = false
entrypoint = "./functions/test-payment-gateway/index.ts"

